{{- if .Values.nfd.enabled }}
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: {{ include "dra-resctrl.fullname" . }}-resctrl-cat
  labels:
    {{- include "dra-resctrl.labels" . | nindent 4 }}
spec:
  rules:
    - name: resctrl-cat
      labels:
        resctrl.fabiendupont.io/resctrl-cat: "true"
      matchFeatures:
        - feature: cpu.cpuid
          matchExpressions:
            CAT_L3:
              op: IsTrue
{{- end }}
